FROM node:latest

# FROM node:lts-alpine

# RUN apk update

RUN npm install --global nodemon

ENV NODE_ENV development

# create root application folder
WORKDIR /usr/src/app/worker

# copy configs to /app folder
COPY package*.json ./
COPY tsconfig.json ./
# copy source code to /app/src folder
COPY ./ /usr/src/app/worker/

RUN npm install

CMD ["npm", "run", "worker.watch"]