FROM node:lts-alpine

RUN apk update

RUN npm install --global nodemon

ENV NODE_ENV development

RUN mkdir -p /usr/src/app/web/node_modules && chown -R node:node /usr/src/app/web

WORKDIR /usr/src/app/web

COPY package*.json ./

COPY tsconfig.json ./

USER node

RUN npm install

COPY --chown=node:node ./ /usr/src/app/web

CMD ["npm", "run", "client.watch"]